# Generated by Django 5.1.1 on 2025-03-26 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('description', models.TextField(default='non')),
            ],
        ),
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('price', models.IntegerField(default=0)),
                ('detail', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=255)),
                ('pdf', models.FileField(upload_to='epathsala/')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epathsala.category')),
            ],
        ),
    ]
