# Generated by Django 5.1.1 on 2025-04-10 03:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epathsala', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
