# Generated by Django 5.1.1 on 2025-04-11 03:37

import django.db.models.deletion
import epathsala.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epathsala', '0003_comment_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='pdf',
            field=models.FileField(upload_to='epathsala/', validators=[epathsala.models.validate_pdf]),
        ),
        migrations.CreateModel(
            name='audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('price', models.IntegerField(default=0)),
                ('detail', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=255)),
                ('audio', models.FileField(upload_to='epathsala/', validators=[epathsala.models.validate_audio_file])),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epathsala.category')),
            ],
        ),
    ]
